title: Fluppisoft
description: >-
  Welcome to Fluppisoft, a game developer from Bavaria.
baseurl: ""
url: "https://fluppisoft.com"

theme: minima

plugins:
  - jekyll-feed

minima:
  skin: dark
  social_links:
    - { platform: instagram, title: Instagram,  user_url: "http://instagram.fluppisoft.com/" }
    - { platform: twitter, title: Twitter, user_url: "http://twitter.fluppisoft.com/" }
    - { platform: youtube, title: Youtube,  user_url: "http://youtube.fluppisoft.com/" }
  
header_pages:
  - index.markdown
  - brick-rigs.markdown
  - blog.markdown
  - imprint.markdown
    
permalink: /blog/:title/