title: Fluppisoft Development Blog
description: >-
  Fluppisoft is a game developer based in Germany.
baseurl: ""
url: "https://blog.fluppisoft.com"

twitter_username: "fluppisoft"
instagram_username: "fluppisoft"

theme: minima

plugins:
  - jekyll-feed

minima:
  skin: auto
  
header_pages:
  - index.markdown
  - imprint.markdown
    
permalink: /:categories/:title/